export const CAROUSEL_PROJECTS = [
  {
    title: 'Lambda Orthodontics Website - Demo',
    description: 'Modern responsive website with functional forms.',
    imageUrl: '/images/screely-lambda.png',
    keywords: ['Healthcare', 'Website', 'Form Validation'],
    actions: [
      'Three fully functional forms with validation',
      'Modern responsive design built with vanilla JavaScript',
    ],
    link: 'https://lambdaortho.vercel.app/',
    tags: ['Web Development', 'Healthcare', 'Forms'],
    slug: 'lambda-orthodontics',
  },
  {
    title: 'Soap Stache',
    description: 'E-commerce platform with shopping cart and Stripe payments.',
    imageUrl: '/images/screely-stache.png',
    keywords: ['E-commerce', 'Next.js', 'Sanity CMS', 'Stripe'],
    actions: [
      'Complete shopping cart and checkout with Stripe integration',
      'Content management through Sanity CMS',
    ],
    link: 'https://app-soap-stache.vercel.app/',
    tags: ['E-commerce', 'Next.js', 'Sanity CMS', 'Stripe'],
    slug: 'soap-stache',
  },
  {
    title: 'I AM [RESIST]',
    description:
      'A powerful headless CMS integration using Notion API with automatic YouTube RSS feeds.',
    imageUrl: '/images/screely-resist.png',
    keywords: ['Headless CMS', 'Notion API', 'Next.js', 'RSS Integration'],
    actions: [
      'Publish content directly from Notion - no deployment needed',
      'Automatic YouTube content aggregation via RSS feeds',
    ],
    link: 'https://iamresist.org',
    tags: ['Web Development', 'Headless CMS', 'Notion API', 'RSS Integration'],
    slug: 'iam-resist',
  },
  {
    title: 'RPG Dice Roller',
    description: 'Interactive dice rolling app for tabletop RPGs.',
    imageUrl: '/images/screely-dice.png',
    keywords: ['Gaming', 'Interactive', 'Web App'],
    actions: [
      'Roll any combination of RPG dice instantly',
      'Track roll history and copy results',
    ],
    link: '/dice-roller',
    tags: ['Web Development', 'Gaming', 'Interactive'],
    slug: 'rpg-dice-roller',
  },
  {
    title: 'Neon Profile Card',
    description:
      'Glassmorphism-inspired ID card with neon CRT glow and animated Matrix Sync terminal sequence.',
    imageUrl: '/images/screely-profilcard.png',
    keywords: ['UI System', 'Tailwind CSS', 'Neon', 'React'],
    actions: [
      'Reusable React component with profile data model and IBM/OCR typography',
      'Animated Matrix Sync terminal sequence with React state and animation hooks',
    ],
    tags: ['UI Design', 'Tailwind CSS', 'Animation', 'React'],
    slug: 'neon-profile-card',
  },
  {
    title: 'IT Consulting',
    description: 'Strategic IT consulting to streamline operations.',
    imageUrl: null,
    keywords: ['IT Consulting', 'Strategic Planning', 'System Integration'],
    actions: [
      'Technology planning and implementation',
      'System optimization and workflow improvement',
    ],
    tags: ['IT Consulting', 'Strategic Planning', 'System Integration'],
    slug: 'it-consulting',
  },
  {
    title: 'Google Analytics',
    description: 'Analytics setup and optimization for tracking.',
    imageUrl: null,
    keywords: ['Analytics', 'Data Tracking', 'Business Intelligence'],
    actions: [
      'Comprehensive tracking setup and configuration',
      'Actionable insights from business data',
    ],
    tags: ['Analytics', 'Data Tracking', 'Business Intelligence'],
    slug: 'google-analytics',
  },
  {
    title: 'n8n Automations',
    description: 'Custom automation workflows to connect apps.',
    imageUrl: null,
    keywords: ['Automation', 'n8n', 'Workflow Integration'],
    actions: [
      'Connect apps and services seamlessly',
      'Automate repetitive tasks and data transfers',
    ],
    tags: ['Automation', 'n8n', 'Workflow Integration'],
    slug: 'n8n-automations',
  },
  {
    title: 'AI Integrations',
    description: 'AI tool integration to enhance workflows.',
    imageUrl: null,
    keywords: ['AI Integration', 'Machine Learning', 'Productivity'],
    actions: [
      'Custom AI solutions for business needs',
      'Enhanced workflows with intelligent automation',
    ],
    tags: ['AI Integration', 'Machine Learning', 'Productivity'],
    slug: 'ai-integrations',
  },
];
